version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: solar
      MYSQL_DATABASE: CitiesIrradiation
      MYSQL_USER: solar
      MYSQL_PASSWORD: solar
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
