// <auto-generated />
using IrradApi.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrradApi.Migrations
{
    [DbContext(typeof(ContextConfig))]
    [Migration("20231107114510_CreatingDatabase")]
    partial class CreatingDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IrradApi.Models.Request.CityIrradiation", b =>
                {
                    b.Property<string>("NameIdentification")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CityIrradiationDataId")
                        .HasColumnType("int");

                    b.HasKey("NameIdentification");

                    b.HasIndex("CityIrradiationDataId");

                    b.ToTable("CityIrradiation");
                });

            modelBuilder.Entity("IrradApi.Models.Request.CityIrradiationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Annual")
                        .HasColumnType("int");

                    b.Property<int>("Apr")
                        .HasColumnType("int");

                    b.Property<int>("Aug")
                        .HasColumnType("int");

                    b.Property<int>("Dec")
                        .HasColumnType("int");

                    b.Property<int>("Feb")
                        .HasColumnType("int");

                    b.Property<int>("Jan")
                        .HasColumnType("int");

                    b.Property<int>("Jul")
                        .HasColumnType("int");

                    b.Property<int>("Jun")
                        .HasColumnType("int");

                    b.Property<float>("Lat")
                        .HasColumnType("float");

                    b.Property<float>("Lon")
                        .HasColumnType("float");

                    b.Property<int>("Mar")
                        .HasColumnType("int");

                    b.Property<int>("May")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nov")
                        .HasColumnType("int");

                    b.Property<int>("Oct")
                        .HasColumnType("int");

                    b.Property<int>("Sep")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CityIrradiationData");
                });

            modelBuilder.Entity("IrradApi.Models.Request.CityIrradiation", b =>
                {
                    b.HasOne("IrradApi.Models.Request.CityIrradiationData", "CityIrradiationData")
                        .WithMany()
                        .HasForeignKey("CityIrradiationDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityIrradiationData");
                });
#pragma warning restore 612, 618
        }
    }
}
